#!/bin/bash
#SBATCH -N 1
#SBATCH -n 8
#SBATCH -o eval2.log
#SBATCH -J eval2
#SBATCH -p skx-normal
#SBATCH -t 02:15:00
#SBATCH --mail-user=joshuaebenezer@utexas.edu
#SBATCH --mail-type=all

conda activate hdr_chipqa

module load python3

ibrun -n 8  python3 tacc_obtain.py --input_folder /scratch/08176/jebeneze/fall2021_hdr_upscaled_yuv/first_half/second_quarter --results_folder ./features/ 
                
