#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -o eval3.log
#SBATCH -J eval3
#SBATCH -p skx-normal
#SBATCH -t 05:15:00
#SBATCH --mail-user=joshuaebenezer@utexas.edu
#SBATCH --mail-type=all

conda activate hdr_chipqa

module load python3

ibrun -n 1 python3 tacc_obtain.py --input_folder /scratch/08176/jebeneze/fall2021_hdr_upscaled_yuv/second_half/third_quarter --results_folder ./features/ 
                
