#!/bin/bash
#SBATCH -N 1
#SBATCH -n 10
#SBATCH -o /work/08176/jebeneze/ls6/code/variable_length_chipqa/eval/etri_eval18.log
#SBATCH -J /work/08176/jebeneze/ls6/code/variable_length_chipqa/eval/etri_eval18
#SBATCH -p normal
#SBATCH -t 03:15:00
#SBATCH --mail-user=joshuaebenezer@utexas.edu
#SBATCH --mail-type=all
source env/bin/activate

conda activate hdr_chipqa

module load python3

ibrun -n 10  python3 tacc_obtain.py --input_folder /scratch/08176/jebeneze/ETRI/ETRI_LIVE_Database/dist_vids/fourth_quarter  --results_folder /work/08176/jebeneze/ls6/code/variable_length_chipqa/etri_multiple_length_chips --time_length 5 --step 30 --database ETRI
            