sbatch scripts/job_0.script
sbatch scripts/job_1.script
sbatch scripts/job_2.script
sbatch scripts/job_3.script
sbatch scripts/job_4.script
sbatch scripts/job_5.script
sbatch scripts/job_6.script
sbatch scripts/job_7.script
sbatch scripts/job_8.script
sbatch scripts/job_9.script
sbatch scripts/job_10.script
sbatch scripts/job_11.script
sbatch scripts/job_12.script
sbatch scripts/job_13.script
sbatch scripts/job_14.script
sbatch scripts/job_15.script
sbatch scripts/job_16.script
sbatch scripts/job_17.script
sbatch scripts/job_18.script
sbatch scripts/job_19.script
sbatch scripts/job_20.script
sbatch scripts/job_21.script
sbatch scripts/job_22.script
sbatch scripts/job_23.script
