import numpy as np
from joblib import dump, load

from sklearn import preprocessing

import argparse
random_seed = 21


parser = argparse.ArgumentParser(description='Test on a video with an SVR that has been trained on the LIVE-HDR dataset with a feature dictionary generated by hdr_chipqa.py')
parser.add_argument('input_feature_file',help='File containing input features generated by hdr_chipqa.py (extension: .z)')
args = parser.parse_args()
sts_kurt_feats = load(args.input_feature_file)


sts_kurt_features = np.reshape(sts_kurt_feats['features'],(1,-1))
grid_svr = load("hdrchipqa_livehdr_trained_svr.z")
scaler =load("hdrchipqa_livehdr_fitted_scaler.z") 
X_train = scaler.transform(sts_kurt_features)
score = grid_svr.predict(X_train)
print(score)

